### ISSUE TITLE
Both Minecrafts Doesn't Work

### ISSUE THREAD

**Issue by MileExcessXD4000** [RailinGames/RailinGames.github.io#11]
When I used Eaglercraft 1.8 and 1.5, I couldn't move or chat. My keyboard wasn't working and I couldn't do anything except for my mouse and esc. Plz try to fix this as soon as you can cuz I have some really good stuff in those accounts

**Comment by 10KisGay** [comment]
you can try and log into mc on this site *https://isacibarra.netlify.app/* its a remade ripoff of old ralin games but all the games work.

**Comment by Cartxrr** [comment]
#10
