### ISSUE TITLE
Railin access

### ISSUE THREAD

**Issue by Complx992** [RailinGames/RailinGames.github.io#18]
I am lovin railin can i be a collaborater and dev editor i have been coding for years now and would really appriciate it, Commy out

**Comment by Cartxrr** [comment]
After reviewing your GitHub profile and repositories, it seems there may be room for improvement in your coding skills. If you have ideas for additional features, feel free to submit them through pull requests. Alternatively, you can connect with me on Discord; my current handle is @burgorkinglover40. Simply share a project you've worked on, and perhaps I'll consider collaborating with you.
