### ISSUE TITLE
Yet

### ISSUE THREAD

**Issue by Complx992** [RailinGames/RailinGames.github.io#19]
I requested to be a part of railin` and recall u saying you would think about it and I was wondering if you decided yet?

**Comment by Hypverr** [comment]
As mentioned earlier, I have reviewed your GitHub profile and didn't find any code that demonstrates your capabilities. If you're working on a project and would like to discuss it further, you can reach me on Discord at @.hypverr.

**Comment by Complx992** [comment]
bro i just joined github iv been coding for 4-5 years

**Comment by Hypverr** [comment]
As mentioned, you can contact me on Discord to prove that, or you can simply just contribute to the project. Depending on that, I may consider inviting you to join the project.

**Comment by ObambaCaree** [comment]
yo u know your site shows ips right?
