### ISSUE TITLE
when i fork most of the games don't show up

### ISSUE THREAD

**Issue by InfinityLoopGames** [RailinGames/RailinGames.github.io#6]
also it says an error
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by Zachary-Rude** [comment]
There are other repositories from railingames that you _also_ need to fork in order for it to work.

**Comment by Cartxrr** [comment]
As Zachary-Rude said there are other repos you need to host this is the one for games https://github.com/RailinGames/files
