### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Trifive** [RailinGames/RailinGames.github.io#9]
The website does not work and is stuck on a screen that says 404 with a button to take you back to the main page that doesn't work.

**Comment by Cartxrr** [comment]
It does work? I checked everything on multiple browsers.

If it doesnt work for you what browser or thing are you using?

**Comment by Trifive** [comment]
I am using railifly.github.io but I'll check again. thanks for making sure
it works

**Comment by Trifive** [comment]
nope, still doesn't work

**Comment by Cartxrr** [comment]
Railifly should work again

**Comment by Trifive** [comment]
it works now, thanks
